### PR TITLE
Fixed integration with refaker2 (raml.schemas support)

### LINKED ISSUE #16: Can't include sub schemas from separate files
I'm having trouble including sub schemas from different files.

Here's an example.
```
git clone https://github.com/thebinarypenguin/raml-example.git
cd raml-example
ramlev spec/api.raml
```

### PR DESCRIPTION
**Pull request by pateketrueke**
I had issues with the `raml.schemas` property, wich is used to define schemas even if aren't used by resources.

Now all schemas are collected and passed to `refaker` for solving references between them.

This would fix #16 since `refaker` is responsible for dereferencing schemas.

### CODE REVIEW

File: src/test.coffee [hunk 1]
```diff
@@ -28,7 +25,8 @@ class Test
     true
 
   schemaVersion: ->
-    if @schema?.contains('$schema')
+    # JSON-schema in RAML are always objects so..
+    if /^[^{]*\{[\s\S]*\}[^}]*/.test(@schema)
```
Comment (cybertk) [inline src/test.coffee]: What does this mean?

File: src/ramlev.coffee [hunk 2]
```diff
@@ -28,15 +28,52 @@ class Ramlev
...
+        cache = []
+
         refaker_keys = ['fakeroot', 'directory']
         refaker_opts = _.pick(config.options, refaker_keys)
-        refaker _.extend({ schemas: extractSchemas(tests) }, refaker_opts), (err, refs, schemas) ->
-          test.json = schemas[test.refaked] for test in tests when test.refaked >= 0
-          chai.tv4.addSchema(id, json) for id, json of refs
+
+        # strategy for faked-schemas
+        refaker_opts.schemas = []
```
Comment (cybertk) [inline src/ramlev.coffee]: Could you encapsulate the shema related logic into a class and add some unit tests?

File: src/test.coffee (hunk 1 above)
Comment (pateketrueke) [inline src/test.coffee]: It will test for a JSON-like object, because a empty object `{}` is valid JSON too.

CSON-Schema will not pass that (?) since braces are not mandatory for the root schema.

I've working on some RAML projects that are using JSON-Schema but missing the `$schema` and `id` property within and works perfectly out of the box.

Further we can use `{ "type": "string" }` as schema and it's perfectly valid for some tools.

This also avoids false positives evaluating empty objects `{}` as CSON-Schema.

**Comment by cybertk** [comment]
Thank you!
